[project]
name = "clickup-api-sprints-analysis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "apscheduler>=3.11.2",
    "fastapi[all]==0.116.1",
    "python-dotenv==1.1.1",
    "requests==2.32.5",
]
